version: "3.9"

services:

  graphql-api:
    image: hubviwe/graphql.api:1.0.2
    restart: on-failure
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5192:80
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1
    hostname: jaeger
    container_name: jaeger
    ports:
      - "6831:6831/udp" # accepts jaeger.thrift over compact thrift protocol
      - "16686:16686" # ui