version: "3.9"

services:

  graphql-api:
    image: hubviwe/graphql.api:1.0.0
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5192:80
      - 7166:443

  token-api:
    image: hubviwe/jwtauthentication.token.api:1.0.6
    hostname: token-api
    container_name: token-api
    environment:
        ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 5161:80