version: "3.9"

services:

  graphql-api:
    image: hubviwe/graphql.api:1.0.2
    restart: on-failure
    build:
        context: src/
        dockerfile: API/Dockerfile
    environment:
        ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5192:80